# Site settings
title: Dineshraj Dhanapathy - Cloud and DevOps Engineer
email: dineshrajdhanapathy@mail.com
description: >-
  Experienced Cloud and DevOps Engineer specializing in AWS, Kubernetes, and modern infrastructure technologies.
  Creating scalable cloud solutions and automated deployment pipelines.
baseurl: "/dineshrajdhanapathy" # the subpath of your site, e.g. /blog
url: "https://dineshrajdhanapathyDD.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DD_Dineshraj
github_username:  dineshrajdhanapathyDD
linkedin_username: dineshraj-dhanapathy-dd-25490058

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Blog settings
blog:
  title: "Blog"
  description: "Insights on cloud technologies, DevOps practices, and software engineering"
  posts_per_page: 10
  excerpt_separator: "<!--more-->"

# Pagination
paginate: 10
paginate_path: "/blog/page/:num/"

# Pagination v2 settings (if using jekyll-paginate-v2)
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing
exclude:
  - .git/
  - .github/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
  - LICENSE

# SEO settings
author: Dineshraj Dhanapathy
logo: /assets/images/logo.png
social:
  name: Dineshraj Dhanapathy
  links:
    - https://www.linkedin.com/in/dineshraj-dhanapathy-dd-25490058
    - https://github.com/dineshrajdhanapathyDD
    - https://twitter.com/DD_Dineshraj

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Dineshraj Dhanapathy"
      show_excerpts: true