# Performance Configuration for Jekyll
# This file contains performance-specific settings

# Asset optimization
sass:
  style: compressed
  sourcemap: never

# Plugin configuration for performance
plugins:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Jekyll Minifier settings
jekyll-minifier:
  uglifier_args:
    harmony: true
  compress_css: true
  compress_javascript: true
  compress_json: true
  simple_doctype: false
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_intertag_spaces: true
  remove_quotes: false
  compress_css: true
  compress_javascript: true
  preserve_ruby: true
  preserve_erb: true
  simple_boolean_attributes: true
  compress_js_templates: true

# Pagination for performance
paginate: 10
paginate_path: "/blog/page/:num/"

# Exclude files from processing to improve build time
exclude:
  - .git/
  - .github/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - webpack.config.js
  - gulpfile.js
  - _scripts/
  - docs/
  - README.md
  - LICENSE
  - "*.log"

# Include only necessary files
include:
  - _pages
  - _posts
  - assets
  - .htaccess
  - _headers
  - sw.js

# Liquid options for performance
liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: true

# Markdown settings for performance
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# Compression settings
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  ignore:
    envs: [development]

# Performance defaults
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:year/:month/:day/:title/"
      
# Build settings for performance
incremental: true
profile: false
safe: false
future: false
unpublished: false
limit_posts: 0

# Development settings
livereload: false
open_url: false

# Cache settings
cache_dir: .jekyll-cache